---
title: "Meeting Notes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "K Knights, PhD Candidate, School of Ecosystem and Forest Sciences"
output: 
  pdf_document:
    df_print: kable
    latex_engine: xelatex
mainfont: Calibri        
fontsize: 11pt
header-includes:
   - \usepackage{setspace}
   - \doublespacing    
---
```{r include=FALSE}
#set global options for code chunks
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

#required packages
#tinytex::install_tinytex()
library(tinytex)
library(knitr)
#"`r format(Sys.time(), '%d %B, %Y')`"

```
Includes notes from last week's meeting (28th April).

* Third year review and going part time: 
  + Hadn't realised that students can only go 50% as part-time, there's no option to choose a different rate.
  + As a result, the budget calculations are a little off and I may have to reduce the part-time period to 5 months instead of six.

* Comparing performance of optimised ds with alternative methods for high density species
  cenopod some common species (and rarer species) in Royal Park, 
  have circumstances where plot based is better, and vice versa and several versions of that
  what parameter combinations lead to plots being better?  Use Guru's work (look at given amount of effort to get 99% of individuals)
  email Kerry re fieldwork risk assessments (get going on paperwork?)
  Pete re plants
  



