---
title: "Methods"
output: 
  pdf_document:
    df_print: kable
    fig_caption: true
    latex_engine: xelatex
mainfont: Calibri 
fontsize: 11pt
header-includes:
   - \usepackage{setspace}
   - \doublespacing
   - \setlength{\parskip}{1em}
---

```{r setup, include=FALSE}
#set global options for code chunks
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

#required packages
#tinytex::install_tinytex()
#tinytex::reinstall_tinytex()
library(tinytex)
source("../scripts/optCalcFunctions.R") 

```

The variance of the estimator of density $\hat{D}$ is approximated by the delta method. For a single species, where $n$ is the total number of detected targets and $\alpha$ is the proportion of detected targets to which distances are measured, this is $$var(\hat{D}) = \hat{D}^{2}\left[\frac{1}{n}\left(1+\frac{1}{2\alpha}\right)\right].$$  In chapter 1 we use the equivalence $n=EL$ as a way to substitute the cost function into this equation to derive the optimal proportion of targets to measure under the constraint of a given budget.  Here we seek to do the same with the cost function expressed for surveys of multiple species, and an objective function comprised of the variances of all species.  We seek to derive the optimal proportion to measure of each species, such that the objective function is minimised for a given budget.

**(move to intro?)** We approach the multiple species context with the awareness that a theoretical optimisation may deliver a solution that is not practical to implement in the field.  In particular, we expect more than two optimal proportions to be prohibitively complex in practice **(elaborate on why...)**.  For this reason, we have constructed our analysis around a two-$\alpha$ *model* *(not the right word)*.  We offer strategies to optimise surveys under the following scenarios:

 * Target species can be considered as either 'common' or 'rare'.  For rare species $\alpha^{*}=1$ (measure distances to all detected targets), and common species are treated as having a single optimal proportion. In this case the key considerations are the point at which a species should be considered rare, where the optimal action is to measure all targets.  *For common species how much information is lost by not fully optimising (vs standard distance sampling? or vs their individual optimal proportions?)*
 * Target species can be considered as either very common or less common; here two optimal proportions, $\alpha^{*}_{A}$ and $\alpha^{*}_{B}$ are appropriate. *There may also be a 'rare' group where all detected targets are measured.*

## Survey budget as a function of shared costs, transect length and encounter rate
 
We base our derivation of expressions to find the optimal proportions to measure in these scenarios on a survey of two species, species A and species B, as this is the simplest context for a multiple species survey. From chapter 1 we have that, for a survey of a single species, $$B = LE(C_{w} + \alpha C_{m}),$$ where $B$ is the total survey budget, $L$ is total transect length, $E$ is the encounter rate, $C_{w}$ is the cost of walking per detection and $C_{m}$ is the cost of measuring per detection. For a simultaneous survey of multiple species, moving along the transect searching for targets is a cost shared by all target species.  To keep the cost of walking independent of the number of species, we must restate the cost of walking as $C_{L}=$ cost of walking per unit length of transect (and $C_{L}=E_{i}C_{w}$, where $E_{i}$ is the encounter rate for species $i$).  We assume $C_{m}$ is the same for all species (assuming no difference in method **(or mean detection distance?)** between species). We can re-express the cost function in terms of $L$, $$L = \frac{B}{C_{L} + E_{A} \alpha _{A}C_{m} + E_{B} \alpha _{B}C_{m}}$$ and substitute this into the variance equation.  First, we must define the objective function to be optimised in the multispecies context.  

## Multiple optimal proportions

We consider the objective function as the sum of the variances on the density estimates for each species:$$var(\hat{D}_{A})+var(\hat{D}_{B})= \hat{D}_{A}^{2} \left(\frac{1}{LE_{A}}+ \frac{1}{2E_{A}\alpha_{A}}\right)+\hat{D}_{B}^{2} \left(\frac{1}{LE_{B}}+ \frac{1}{2E_{B}\alpha_{B}}\right).$$  **Why the sum? Because the product was super complex.**  To find the optimal values of $\alpha_{A}$ and $\alpha_{B}$ - where the overall variance is minimised - we differentiate and solve for $0$ the two partial derivatives of equation X with respect to $\alpha_{A}$ and $\alpha_{B}$.  The resulting simultaneous equations are solved for $\alpha_{A}$ and $\alpha_{B}$.  If all variables are $>0$, we have $$\alpha^{*}_{A} = \frac{D_{A}\sqrt{\frac{C_{L}E_{B}}{C_{m}D_{B}^{2}E_{A}^{2}+C_{m}D_{A}^{2}E_{A}E_{B}}}}{\sqrt{2}}$$ and $$\alpha^{*}_{B} = \frac{D_{B}\sqrt{\frac{C_{L}E_{A}}{C_{m}D_{A}^{2}E_{B}^{2}+C_{m}D_{B}^{2}E_{A}E_{B}}}}{\sqrt{2}}.$$  Distance sampling theory says that the encounter rate $E$ is equal to $2\mu D$, where $\mu$ is the 'effective strip half-width', or the distance at which the survey area would yield the same $n$ under perfect detection as the survey with strip half-width $w$ yields with imperfect detection described by the detection function. With this we can rearrange and simplify the above equations for the distance sampling context:$$\alpha_{A} = \frac{\sqrt{\frac{C_{L}}{C_{m}}\frac{\mu_{B}/\mu_{A}}{\mu_{A}D_{B}+\mu_{B}D_{A}}}}{2}$$ and $$\alpha_{B} = \frac{\sqrt{\frac{C_{L}}{C_{m}}\frac{\mu_{A}/\mu_{B}}{\mu_{B}D_{A}+\mu_{A}D_{B}}}}{2}.$$ If we consider the case where species A and species B have the same density and detectability, these expressions simplify to our expression for the $\alpha^{*}$ from Chapter 1.

Equations X and X give us expressions to find the optimal proportions to measure for species A and species B, where the ratio of costs $C = \frac{C_{L}}{C_{m}}$ **(different to the other ratio of costs)** provides a weighting factor to the expression $\frac{\mu_{B}/\mu_{A}}{\mu_{A}D_{B}+\mu_{B}D_{A}}$.  That is, the ratio of effective strip half-width (opposing species as the numerator) divided by the sum of the densities, where the densities are weighted by the opposing species effective strip half-width.  Conceptually, this expression is unintuitive, and under survey conditions it is not feasible to have pre-existing accurate estimates for all the variables involved in order to calculate the optimal proportions - indeed, it is probably the estimation of density for which the survey is undertaken. Therefore, we seek to provide an expression that requires minimal pre-existing data to calculate the optimal proportions.  

For our first survey strategy $\alpha^{*}_{A}=1$ and $\alpha^{*}_{B}<1$, or more precisely, $\alpha_{A}\ge 1$: the maximum proportion of targets to measure is 1, but the direct calculation may give a proportion $>1$. We are interested in relationships between characteristics of species A and species B that drive the optimal proportion for one of the species to 1 or greater.  From equations X and X, we see that the expression inside the radical should be $\ge4$ for $\alpha\ge1$, or $<4$ for $\alpha<1$. We can solve these inequalities for the cost ratio, giving a region of values for the cost ratio where these conditions are satisfied.  Where species A is the rare species and $\alpha_{A}\ge 1$, $\mu_{A}<\mu_{B}$ and $$\frac{4\mu_{A}(\mu_{A}D_{B}+\mu_{B}D_{A})}{\mu_{B}}\le C<\frac{4\mu_{B}(\mu_{B}D_{A}+\mu_{A}D_{B})}{\mu_{A}}.$$ It is also prudent to note when $\alpha^{*}\ge1$ for both species A and species B, i.e. when the optimal strategy is to measure all targets of all species.  When $\mu_{A}\le\mu_{B}$ $$C\ge \frac{4\mu_{B}(\mu_{A}D_{B}+\mu_{B}D_{A})}{\mu_{A}}.$$  When $\mu_{A}>\mu_{B}$ $$C\ge\frac{4\mu_{A}(\mu_{A}D_{B}+\mu_{B}D_{A})}{\mu_{B}}.$$

Our alternative strategy, where both optimal proportions are below 1, 


## Case studies 
 
To test the expression for optimising multiple species surveys, we data from Junaedi (2018)
